#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "planka"
name = "Planka"
description.en = "Realtime kanban board for workgroups"
description.fr = "Tableau Kanban en temps réel pour les groupes de travail"

version = "2.0.3~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0"
website = "https://planka.app/"
demo = "https://plankanban.github.io/planka/#/"
admindoc = "https://docs.planka.cloud/docs/intro/"
code = "https://github.com/plankanban/planka"

[integration]
yunohost = ">= 12.1.17"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = true

ldap = false
sso = false

disk = "50M"
ram.build = "500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"
    
    [install.language]
    ask.en = "Choose the default application language"
    ask.fr = "Choisissez la langue par défaut de l'application"
    type = "select"
    choices = ["ar_YE", "bg_BG", "ca_ES", "cs_CZ", "da_DK", "de_DE", "el_GR", "en_GB", "en_US", "es_ES", "et_EE", "fa_IR", "fi_FI", "fr_FR", "hu_HU", "id_ID", "it_IT", "ja_JP", "ko_KR", "nl_NL", "pl_PL", "pt_BR", "pt_PT", "ro_RO", "ru_RU", "sk_SK", "sr_Cyrl_RS", "sr_Latn_RS", "sv_SE", "tr_TR", "uk_UA", "uz_UZ", "vi_VN", "zh_CN", "zh_TW"]
    default = "en_US"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/plankanban/planka/releases/download/v2.0.3/planka-prebuild.zip"
        sha256 = "30d3f8d6b499c0e7e97b7c4fb19186705476ac98dcd8f73d880f86e2b73513ad"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "^planka-prebuild.zip$"
    
        [resources.sources.v1]
        url = "https://github.com/plankanban/planka/releases/download/v1.26.3/planka-prebuild.zip"
        sha256 = "d7baf78718676245a42511d1c52837dfbeef8ef176b7c22177f909c9d5039ddc"
        prefetch = false

    [resources.system_user]
    allow_email = true

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false
    api.protected = true

    [resources.ports]
    socket.default = 1337
    
    [resources.apt]
    packages = "postgresql, postgresql-contrib, build-essential"

    [resources.database]
    type = "postgresql", build-essential

    [resources.nodejs]
    version = "22"
